// Code generated by Kitex v0.6.2. DO NOT EDIT.

package videocenter

import (
	"context"
	videoCenter "douyin-backend/video-center/kitex_gen/videoCenter"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Feed(ctx context.Context, Req *videoCenter.DouyinFeedRequest, callOptions ...callopt.Option) (r *videoCenter.DouyinFeedResponse, err error)
	PublishList(ctx context.Context, Req *videoCenter.DouyinPublishListRequest, callOptions ...callopt.Option) (r *videoCenter.DouyinPublishListResponse, err error)
	PublishAction(ctx context.Context, Req *videoCenter.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *videoCenter.DouyinPublishActionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoCenterClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoCenterClient struct {
	*kClient
}

func (p *kVideoCenterClient) Feed(ctx context.Context, Req *videoCenter.DouyinFeedRequest, callOptions ...callopt.Option) (r *videoCenter.DouyinFeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, Req)
}

func (p *kVideoCenterClient) PublishList(ctx context.Context, Req *videoCenter.DouyinPublishListRequest, callOptions ...callopt.Option) (r *videoCenter.DouyinPublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishList(ctx, Req)
}

func (p *kVideoCenterClient) PublishAction(ctx context.Context, Req *videoCenter.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *videoCenter.DouyinPublishActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishAction(ctx, Req)
}
