gin:
  port: 9421

elasticsearch:
  address: DouyinDBA.raqtpie.xyz
  port: 9200
  user: elastic
  password: 

gRPC:
  address: 192.168.1.12
  port: 9422

nacos:
  address: 192.168.126.128
  port: 8848
  group: Douyin_GROUP
  namespaceId: ""
  server-name: chat-center