server:
  host: http://127.0.0.1
  port: 3000

mysql:
  DB: mysql
  DbHost: DouyinDBA.raqtpie.xyz
  DbPort: 3306
  DbUser: DouyinDBA
  DbPassword: nibainimane
  DbName: DouyinDB

redis:
  RedisDb: redis
  RedisAddr: 192.168.88.130:6379

  RedisPw: rh2004..
  RedisDbName: 2