// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.0--rc3
// source: video_interaction.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DouyinVideoInteractionService_ActionFavorite_FullMethodName = "/douyin.extra.first.DouyinVideoInteractionService/ActionFavorite"
	DouyinVideoInteractionService_ListFavorite_FullMethodName   = "/douyin.extra.first.DouyinVideoInteractionService/ListFavorite"
	DouyinVideoInteractionService_CountFavorite_FullMethodName  = "/douyin.extra.first.DouyinVideoInteractionService/CountFavorite"
	DouyinVideoInteractionService_ActionComment_FullMethodName  = "/douyin.extra.first.DouyinVideoInteractionService/ActionComment"
	DouyinVideoInteractionService_ListComment_FullMethodName    = "/douyin.extra.first.DouyinVideoInteractionService/ListComment"
)

// DouyinVideoInteractionServiceClient is the client API for DouyinVideoInteractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DouyinVideoInteractionServiceClient interface {
	// 点赞操作
	ActionFavorite(ctx context.Context, in *DouyinFavoriteActionRequest, opts ...grpc.CallOption) (*DouyinFavoriteActionResponse, error)
	// 点赞列表
	ListFavorite(ctx context.Context, in *DouyinFavoriteListRequest, opts ...grpc.CallOption) (*DouyinFavoriteListResponse, error)
	// 点赞数量
	CountFavorite(ctx context.Context, in *DouyinFavoriteCountRequest, opts ...grpc.CallOption) (*DouyinFavoriteCountResponse, error)
	// 评论操作
	ActionComment(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentActionResponse, error)
	// 评论列表
	ListComment(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error)
}

type douyinVideoInteractionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDouyinVideoInteractionServiceClient(cc grpc.ClientConnInterface) DouyinVideoInteractionServiceClient {
	return &douyinVideoInteractionServiceClient{cc}
}

func (c *douyinVideoInteractionServiceClient) ActionFavorite(ctx context.Context, in *DouyinFavoriteActionRequest, opts ...grpc.CallOption) (*DouyinFavoriteActionResponse, error) {
	out := new(DouyinFavoriteActionResponse)
	err := c.cc.Invoke(ctx, DouyinVideoInteractionService_ActionFavorite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *douyinVideoInteractionServiceClient) ListFavorite(ctx context.Context, in *DouyinFavoriteListRequest, opts ...grpc.CallOption) (*DouyinFavoriteListResponse, error) {
	out := new(DouyinFavoriteListResponse)
	err := c.cc.Invoke(ctx, DouyinVideoInteractionService_ListFavorite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *douyinVideoInteractionServiceClient) CountFavorite(ctx context.Context, in *DouyinFavoriteCountRequest, opts ...grpc.CallOption) (*DouyinFavoriteCountResponse, error) {
	out := new(DouyinFavoriteCountResponse)
	err := c.cc.Invoke(ctx, DouyinVideoInteractionService_CountFavorite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *douyinVideoInteractionServiceClient) ActionComment(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentActionResponse, error) {
	out := new(DouyinCommentActionResponse)
	err := c.cc.Invoke(ctx, DouyinVideoInteractionService_ActionComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *douyinVideoInteractionServiceClient) ListComment(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error) {
	out := new(DouyinCommentListResponse)
	err := c.cc.Invoke(ctx, DouyinVideoInteractionService_ListComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DouyinVideoInteractionServiceServer is the server API for DouyinVideoInteractionService service.
// All implementations must embed UnimplementedDouyinVideoInteractionServiceServer
// for forward compatibility
type DouyinVideoInteractionServiceServer interface {
	// 点赞操作
	ActionFavorite(context.Context, *DouyinFavoriteActionRequest) (*DouyinFavoriteActionResponse, error)
	// 点赞列表
	ListFavorite(context.Context, *DouyinFavoriteListRequest) (*DouyinFavoriteListResponse, error)
	// 点赞数量
	CountFavorite(context.Context, *DouyinFavoriteCountRequest) (*DouyinFavoriteCountResponse, error)
	// 评论操作
	ActionComment(context.Context, *DouyinCommentActionRequest) (*DouyinCommentActionResponse, error)
	// 评论列表
	ListComment(context.Context, *DouyinCommentListRequest) (*DouyinCommentListResponse, error)
	mustEmbedUnimplementedDouyinVideoInteractionServiceServer()
}

// UnimplementedDouyinVideoInteractionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDouyinVideoInteractionServiceServer struct {
}

func (UnimplementedDouyinVideoInteractionServiceServer) ActionFavorite(context.Context, *DouyinFavoriteActionRequest) (*DouyinFavoriteActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActionFavorite not implemented")
}
func (UnimplementedDouyinVideoInteractionServiceServer) ListFavorite(context.Context, *DouyinFavoriteListRequest) (*DouyinFavoriteListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFavorite not implemented")
}
func (UnimplementedDouyinVideoInteractionServiceServer) CountFavorite(context.Context, *DouyinFavoriteCountRequest) (*DouyinFavoriteCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountFavorite not implemented")
}
func (UnimplementedDouyinVideoInteractionServiceServer) ActionComment(context.Context, *DouyinCommentActionRequest) (*DouyinCommentActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActionComment not implemented")
}
func (UnimplementedDouyinVideoInteractionServiceServer) ListComment(context.Context, *DouyinCommentListRequest) (*DouyinCommentListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComment not implemented")
}
func (UnimplementedDouyinVideoInteractionServiceServer) mustEmbedUnimplementedDouyinVideoInteractionServiceServer() {
}

// UnsafeDouyinVideoInteractionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DouyinVideoInteractionServiceServer will
// result in compilation errors.
type UnsafeDouyinVideoInteractionServiceServer interface {
	mustEmbedUnimplementedDouyinVideoInteractionServiceServer()
}

func RegisterDouyinVideoInteractionServiceServer(s grpc.ServiceRegistrar, srv DouyinVideoInteractionServiceServer) {
	s.RegisterService(&DouyinVideoInteractionService_ServiceDesc, srv)
}

func _DouyinVideoInteractionService_ActionFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinFavoriteActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DouyinVideoInteractionServiceServer).ActionFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DouyinVideoInteractionService_ActionFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DouyinVideoInteractionServiceServer).ActionFavorite(ctx, req.(*DouyinFavoriteActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DouyinVideoInteractionService_ListFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinFavoriteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DouyinVideoInteractionServiceServer).ListFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DouyinVideoInteractionService_ListFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DouyinVideoInteractionServiceServer).ListFavorite(ctx, req.(*DouyinFavoriteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DouyinVideoInteractionService_CountFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinFavoriteCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DouyinVideoInteractionServiceServer).CountFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DouyinVideoInteractionService_CountFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DouyinVideoInteractionServiceServer).CountFavorite(ctx, req.(*DouyinFavoriteCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DouyinVideoInteractionService_ActionComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinCommentActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DouyinVideoInteractionServiceServer).ActionComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DouyinVideoInteractionService_ActionComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DouyinVideoInteractionServiceServer).ActionComment(ctx, req.(*DouyinCommentActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DouyinVideoInteractionService_ListComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinCommentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DouyinVideoInteractionServiceServer).ListComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DouyinVideoInteractionService_ListComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DouyinVideoInteractionServiceServer).ListComment(ctx, req.(*DouyinCommentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DouyinVideoInteractionService_ServiceDesc is the grpc.ServiceDesc for DouyinVideoInteractionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DouyinVideoInteractionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "douyin.extra.first.DouyinVideoInteractionService",
	HandlerType: (*DouyinVideoInteractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActionFavorite",
			Handler:    _DouyinVideoInteractionService_ActionFavorite_Handler,
		},
		{
			MethodName: "ListFavorite",
			Handler:    _DouyinVideoInteractionService_ListFavorite_Handler,
		},
		{
			MethodName: "CountFavorite",
			Handler:    _DouyinVideoInteractionService_CountFavorite_Handler,
		},
		{
			MethodName: "ActionComment",
			Handler:    _DouyinVideoInteractionService_ActionComment_Handler,
		},
		{
			MethodName: "ListComment",
			Handler:    _DouyinVideoInteractionService_ListComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video_interaction.proto",
}
