// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.0--rc3
// source: comment.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CommentCenter_ActionComment_FullMethodName = "/douyin.comment.comment_center/ActionComment"
	CommentCenter_ListComment_FullMethodName   = "/douyin.comment.comment_center/ListComment"
)

// CommentCenterClient is the client API for CommentCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentCenterClient interface {
	// 评论操作
	ActionComment(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentActionResponse, error)
	// 评论列表
	ListComment(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error)
}

type commentCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentCenterClient(cc grpc.ClientConnInterface) CommentCenterClient {
	return &commentCenterClient{cc}
}

func (c *commentCenterClient) ActionComment(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentActionResponse, error) {
	out := new(DouyinCommentActionResponse)
	err := c.cc.Invoke(ctx, CommentCenter_ActionComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentCenterClient) ListComment(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error) {
	out := new(DouyinCommentListResponse)
	err := c.cc.Invoke(ctx, CommentCenter_ListComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentCenterServer is the server API for CommentCenter service.
// All implementations must embed UnimplementedCommentCenterServer
// for forward compatibility
type CommentCenterServer interface {
	// 评论操作
	ActionComment(context.Context, *DouyinCommentActionRequest) (*DouyinCommentActionResponse, error)
	// 评论列表
	ListComment(context.Context, *DouyinCommentListRequest) (*DouyinCommentListResponse, error)
	mustEmbedUnimplementedCommentCenterServer()
}

// UnimplementedCommentCenterServer must be embedded to have forward compatible implementations.
type UnimplementedCommentCenterServer struct {
}

func (UnimplementedCommentCenterServer) ActionComment(context.Context, *DouyinCommentActionRequest) (*DouyinCommentActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActionComment not implemented")
}
func (UnimplementedCommentCenterServer) ListComment(context.Context, *DouyinCommentListRequest) (*DouyinCommentListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComment not implemented")
}
func (UnimplementedCommentCenterServer) mustEmbedUnimplementedCommentCenterServer() {}

// UnsafeCommentCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentCenterServer will
// result in compilation errors.
type UnsafeCommentCenterServer interface {
	mustEmbedUnimplementedCommentCenterServer()
}

func RegisterCommentCenterServer(s grpc.ServiceRegistrar, srv CommentCenterServer) {
	s.RegisterService(&CommentCenter_ServiceDesc, srv)
}

func _CommentCenter_ActionComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinCommentActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentCenterServer).ActionComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentCenter_ActionComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentCenterServer).ActionComment(ctx, req.(*DouyinCommentActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentCenter_ListComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinCommentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentCenterServer).ListComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentCenter_ListComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentCenterServer).ListComment(ctx, req.(*DouyinCommentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentCenter_ServiceDesc is the grpc.ServiceDesc for CommentCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "douyin.comment.comment_center",
	HandlerType: (*CommentCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActionComment",
			Handler:    _CommentCenter_ActionComment_Handler,
		},
		{
			MethodName: "ListComment",
			Handler:    _CommentCenter_ListComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comment.proto",
}
